### ISSUE TITLE
Installing 'OneMobileSDK-Swift3' using Cocoapods causes error

### ISSUE THREAD

**Issue by vitamel** [vidible/OneMobileSDK-releases#1]
@AndriiMoskvin,  @Berk0ld

Xcode 8.2.1 doesn't allow to use latest 2.0.1139 version and shows error - "Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2"

**Comment by AndriiMoskvin** [comment]
@vitamel Thanks for reporting - we will update our CI to make it compilable with Xcode 8.2.1 and Swift 3.0.2

**Comment by AndriiMoskvin** [comment]
Done.

**Comment by vitamel** [comment]
@AndriiMoskvin Can you tell when should we expect updated version with this fix?

**Comment by AndriiMoskvin** [comment]
@vitamel Sorry - we have some troubles with CI - I will fix them and notify you. Expect it today.

**Comment by AndriiMoskvin** [comment]
@vitamel Travis experiencing some issues with Mac OS builds - we have a lot of them in queue, so update is still not there 😞

**Comment by AndriiMoskvin** [comment]
@vitamel Travis back to work. SDK 2.1.1172 is compiled with Xcode 8.2. Ready to use.
