### ISSUE TITLE
How to use OneMobileSDK version 2.x compiled with Swift 3.1?

### ISSUE THREAD

**Issue by zhabko** [vidible/OneMobileSDK-releases#4]
hi! want to use OneMobileSDK compiled with Swift 3.1, having the following problems:

1. pod 'OneMobileSDK-Swift3' downloads version 2.1.1180 which is complied with Swift 3.0 and not compatible with our project.
as far as I got, versions 2.4 and higher are built with Swift 3.1.
=> could you please advise the correct way to add it using pods?

2. tried to download version 2.4 directly from https://github.com/vidible/OneMobileSDK-releases/releases/download/2.4/OneMobileSDK.framework.zip and added the frameworks manually to the project.
it works using the following code:
            OneSDK.Provider.default.getSDK()
                .then { $0.getPlayer(videoID: video.vidibleId) }
                .dispatch(on: .main)
                .onSuccess { player in
                    let playerViewController = PlayerViewController()
                    playerViewController.contentControlsViewController = DefaultControlsViewController()
                    playerViewController.player = player
                    self.navigationController?.pushViewController(playerViewController, animated: true)
                }
                .onError { error in
                    let alert = UIAlertController(title: "Error",
                                                  message: "\(error)",
                        preferredStyle: .alert)
                    alert.addAction(UIAlertAction(title: "OK",
                                                  style: .default,
                                                  handler: nil))
                    self.present(alert, animated: true, completion: nil)
            }
=> it's good, videos are played successfully, but PlayerViewController looks to be intended opening as full screen only.
is there are any way to add it as a subview to the parent view controller? it's required by our designs, but shows as just black area when trying to do
                    self.view.addSubview(playerViewController.view)

3. can you point me to some actual documentation on it? i know only this place and it looks to be out-dated http://vidible.github.io/mobile-sdk-ios/

Many thanks in advance!

**Comment by zhabko** [comment]
@AndriiMoskvin, @Berk0ld could you please help me with the questions above?

**Comment by AndriiMoskvin** [comment]
@zhabko 
1. Just use `pod update` and it will download latest stable version.
2. You can add `PlayerViewController` as a child view controller. [Apple Guide](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html).
3. There is no documentation for the SDK - instead you can use [our examples repo](https://github.com/vidible/OneMobileSDK-playground-ios).

**Comment by zhabko** [comment]
great, thanks for you reply, @AndriiMoskvin! will try and close the issue.

**Comment by AlexeyDemedetskiy** [comment]
Also, you can create and display player view controller independently from setting player into it.

**Comment by zhabko** [comment]
@AndriiMoskvin, @Berk0ld many thanks again for your advices, it works for me now.

And more important question regarding ads.

As for now, our backend returns video urls as https links to some .m3u8 files and we're appending them with some ads tags like &ad=mobile&ad.preroll=1
We're also getting vidible id-s from the backend and now we're able to play them using OneMobileSDK - but what about ads?
As far as I can see, OneMobileSDK contains some functionality for it - but could you please provide me with some details how to configure it properly?

**Comment by AndriiMoskvin** [comment]
@zhabko Ads are configured on Vidible Portal. You don't need to do any additional setups on client side.

**Comment by zhabko** [comment]
@AndriiMoskvin that sounds really great, thank you!
But if so, the next question: is it possible to switch ads on/off for some particular video on client side?

What's why I'm asking - as for now, we're having the following logic: if the video is opened from the feed page (some list of video thumbnails) - no ads tags added. However, when video play ends, next video started automatically, and ads tags need to be added for it. So we need some way to control that to keep the current logic.

**Comment by AndriiMoskvin** [comment]
On client side there is no such possibility. It is all configured from the Vidible Portal.

**Comment by zhabko** [comment]
@AndriiMoskvin got you, many thanks for all your help!
closing this issue for now, just FYI: we're still waiting for the decision from our management  if we'll use your SDK, just consider my initial investigation is done.

**Comment by MarkGerl** [comment]
@zhabko for more ads-related details, email video.support@teamaol.com.  The SDK has a way to configure multiple simultaneous ad experiences, which you can request on a per-section of your app basis .. to get this all configured, ping the support folks, and cc me (mark.gerl@teamaol.com).
